### PR TITLE
Add typescript/jest

### PR DESCRIPTION
**Pull request by staab**
Feel free to pick and choose or ignore this completely, just wanted to expedite the process as I'm able.

### CODE REVIEW

**Comment by paulmillr** [comment]
I suggest we keep my micro-should because it's just 200 lines of code and no dependencies, we just fix its version to 0.4.0 and it never changes

**Comment by staab** [comment]
That's fine with me, I was just guessing which library you were using. I've also added a readme with usage as well.

**Comment by staab** [comment]
Just updated to micro-should with chai. Some of the tests aren't passing any more though. We should probably rename salt to nonce in the vectors as well.

**Comment by paulmillr** [comment]
We don't need chai: we have `node:assert`.

I should have uploaded tsconfig and updated vectors before you've spent your time on this - sorry. Check out the branch now.

**Comment by paulmillr** [comment]
List of remaining tasks:

- NIP-44 has been designed as a sub-component of NIP-01. This relation should be added to the specification.
- Some parts of the specification directly refer to NIP-01. It would be helpful to identify these parts. For example, the message serialization and signature generation specified in NIP-01 are not mentioned in the current specification of the encryption, but are included in the specification of the decryption.
- It would be helpful if the example given to demonstrate the protocol included some intermediate values, such as the conversation_key and the message keys.
- The formats of public and private keys are not specified. To avoid confusion, it would be helpful to define the formats. As discussed, the formats used for private key and public key are the same as the ones used for Schnorr signatures (BIP-340). Key validation should include a check that the public key is not 0 and represents a point on the curve.
- For ECDH the two private keys d and n-d (where n is the order of the elliptic curve) are equivalent. Both d and n-d result in the same public key, since the public key only consists of the x coordinate of the scalar multiplication d*G and (n-d)*G. The x coordinate of the ECDH exchange also does not depend on whether d and n-d are being used for the computation. However, the choice is relevant for Schnorr signatures where the private key is selected among d and n-d, such that the y coordinate of the corresponding public key is an even integer. To avoid confusion, it should be clarified in the specification whether the key generation for NIP44 can generate arbitrary private keys. If so, any joint-use of keys for ECDH and Schnorr signatures needs to include adjustment of private keys when signing.
- It would make sense to add test vectors with truncated cipher-texts to check for out-of-bound access instances. Implementations should throw or return an error instead of going into panic mode. For example, adding the following truncated ciphertexts is advised:
    - a ciphertext of size 0 to check for out-of-bound access during version check;
    - ciphertexts of size 1..32 to check for out-of-bound access for the salt;
    - ciphertexts of size 33..64 to check for out-of-bound access for the MAC.

**Comment by staab** [comment]
No worries, I'll see if I can help with items 1 and 2 in that list to start. Also, the tests aren't passing for me, looks like just error messages. Are the vectors correct or the code?

**Comment by paulmillr** [comment]
all valid vectors are passing. invalid vectors I still need to prepare, you can comment them out

**Comment by paulmillr** [comment]
if you could help with 1 and 2 , we can finalize this soon

**Pull request closed without merging**
