### PR TITLE
F# implementation

### LINKED ISSUE #5: Copy F# implementation
https://github.com/lontivero/Nostra/pull/17/files

@lontivero would you be open to copying the great stuff in the repository? This would make discoverability better, and would be cool for learning purposes.

### PR DESCRIPTION
**Pull request by lontivero**
Close #5

This PR copies and adapts the implementation from the Nostra project. All the 101 tests for **valid** cases pass green but none of the invalid cases were tested.

Nostra license in GPL2 but I have no problem with this code being copied and I can give MIT license if you think it is important.

### CODE REVIEW

**Comment by paulmillr** [comment]
I don’t think gpl is important. It would have been important if it was the only nip44 impl, because “derived code” must also be gpl. Since we have other impls, users can look at them as well.

Re: invalid vectors — please add tests against them whenever you’ll have time. They validate important cryptographic parts. If the underlying secp implementation is shit, it’s possible to execute twist attacks. Vectors ensure it’s not shit.

**Comment by paulmillr** [comment]
Thanks!

**Comment by paulmillr** [comment]
@lontivero when copying, it's necessary to copy license file as well. I've copied GPL for now.

**Comment by lontivero** [comment]
Sorry for the delay. I see you have already added the license file.

**Pull request merged**
